In [32]:
!pip install BVCscrap

Requirement already satisfied: BVCscrap in c:\users\hp 1030 g7\anaconda3\lib\site-packages (0.2.1)

In [33]:
import BVCscrap as load

In [34]:
data=load.loadata('ATW')
data.head()

TypeError: can only concatenate str (not "NoneType") to str

In [ ]:
load.notation()

In [ ]:
data=load.loadata('Attijariwafa')
data.head()

In [ ]:
data.dtypes

In [ ]:
data.shape

In [ ]:
data.index

In [ ]:
data.shape

In [ ]:
import BVCscrap as load
import pandas as pd

In [ ]:
data=load.loadata('Attijariwafa')

In [ ]:
data.shape

In [ ]:
data.info()

In [ ]:
data.index

In [ ]:
data.isnull().sum()

In [ ]:
conversion=pd.to_datetime(data.index, dayfirst=True)
conversion

In [ ]:
data.index=conversion
data.head()

In [ ]:
data=data.reset_index()
data.head()

In [ ]:
data['ticker']='ATW'
data.head()

In [ ]:
data=data.rename(columns={ 'Date': 'date',
    'Value': 'value',
    'Min': 'min',
    'Max': 'max',
    'Variation': 'variation',
    'Volume': 'volume'})
data.head()

In [ ]:
import sqlite3
connexion = sqlite3.connect(r"C:\Users\HP 1030 G7\Desktop\casa_market.db")

In [ ]:
data.to_sql('cours', connexion, if_exists='append', index=False)

In [ ]:
connexion.commit()
connexion.close()

In [35]:
connexion = sqlite3.connect(r"C:\Users\HP 1030 G7\Desktop\casa_market.db")

In [36]:
def charger_societes(nom, ticker):
    data=load.loadata(nom)
    data.index=pd.to_datetime(data.index,dayfirst=True)
    data=data.reset_index()
    data['ticker']=ticker
    data=data.rename(columns={'Value':'value','Date':'date','Min':'min','Max': 'max', 'Variation': 'variation', 'Volume': 'volume'})
    data.to_sql('cours',connexion, if_exists='append',index=False)

In [37]:
charger_societes('Maroc Telecom', 'IAM')
charger_societes('BCP', 'BCP')
charger_societes('LafargeHolcim', 'LHM')

IntegrityError: UNIQUE constraint failed: cours.ticker, cours.date

In [38]:
connexion.execute('DELETE FROM cours')
connexion.commit()
print('cours videe')

cours videe

In [40]:
import pandas as pd
pd.read_sql('SELECT COUNT(*) FROM cours', connexion)

   COUNT(*)
0         0

In [41]:
charger_societes('Attijariwafa', 'ATW')
charger_societes('Maroc Telecom', 'IAM')
charger_societes('BCP', 'BCP')
charger_societes('LafargeHolcim', 'LHM')

In [42]:
pd.read_sql("SELECT ticker, COUNT(*) AS nb FROM cours GROUP BY ticker", connexion)

  ticker    nb
0    ATW  1242
1    BCP  1242
2    IAM  1242
3    LHM  1242

In [43]:
connexion.commit()